FROM rasa/rasa-sdk:3.6.2

USER root

WORKDIR /app

COPY ./actions /app/actions
COPY ./actions/actions_requirements.txt /app/actions/actions_requirements.txt

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r /app/actions/actions_requirements.txt

# Trở lại user mặc định của rasa-sdk
USER 1001

EXPOSE 5055

ENTRYPOINT []

CMD ["python", "-m", "rasa_sdk", "--actions", "actions"]
